service:
  name: xdd-tribute

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

package:
  include:
    - firebase-admin-service-account.json

functions:
  thank:
    handler: src/handler.handlerThank
    environment:
      DATABASE_NAME: ${env:DATABASE_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: firebase-admin-service-account.json
      SLACK_TOKEN: ${env:SLACK_TOKEN}
  getThanks:
    handler: src/handler.handlerGetThanks
    environment:
      DATABASE_NAME: ${env:DATABASE_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: firebase-admin-service-account.json
  updateThank:
    handler: src/handler.handlerUpdateThank
    environment:
      DATABASE_NAME: ${env:DATABASE_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: firebase-admin-service-account.json
  slack:
    handler: src/handler.handlerSlack
    environment:
      DATABASE_NAME: ${env:DATABASE_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: firebase-admin-service-account.json
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      SIGNING_SECRET: ${env:SIGNING_SECRET}
    events:
      - http:
          method: post
          path: slack
