name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    setps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - name: deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
