name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: |
          npm install
          npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}