name: CI/CD Prod

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Decrypt firebase admin service account
        run: .github/scripts/decrypt_secret.sh
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: |
          npm install
          npm test
          npm run deploy:prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          IS_PROD: true
